version: '3.8'

services:
  zonos:
    build:
      context: .
      dockerfile: Dockerfile
    image: svenbayer/zonos-api:v0.1.1
    container_name: zonos-api

    # Start the API server
    # command: ["python3", "zonos_api.py"]
    
    # Use NVIDIA runtime for GPU
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0

    # Mount reference audio folder
    volumes:
      - ./zonos/ref_audio:/app/ref_audio
      - ./zonos/huggingface:/root/.cache/huggingface
      - ./zonos/tmp:/app/tmp

    # Share the host network stack
    # (This makes the container’s port 7861 available directly on the host)
    network_mode: "host"
    ports:
      - "7861:7861"

    # So you can attach an interactive shell if needed
    stdin_open: true
    tty: true
    
    #
    # Then you can access http://localhost:7861/status from outside.
